// Generated by gencpp from file ROS_SplinePathMotionProfiling/GetNavCriteriaPlanRequest.msg
// DO NOT EDIT!


#ifndef ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVCRITERIAPLANREQUEST_H
#define ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVCRITERIAPLANREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ROS_SplinePathMotionProfiling
{
template <class ContainerAllocator>
struct GetNavCriteriaPlanRequest_
{
  typedef GetNavCriteriaPlanRequest_<ContainerAllocator> Type;

  GetNavCriteriaPlanRequest_()
    : acceleration(0.0)
    , max_linear_speed(0.0)
    , max_angular_speed(0.0)
    , max_centripetal_acceleration(0.0)  {
    }
  GetNavCriteriaPlanRequest_(const ContainerAllocator& _alloc)
    : acceleration(0.0)
    , max_linear_speed(0.0)
    , max_angular_speed(0.0)
    , max_centripetal_acceleration(0.0)  {
  (void)_alloc;
    }



   typedef double _acceleration_type;
  _acceleration_type acceleration;

   typedef double _max_linear_speed_type;
  _max_linear_speed_type max_linear_speed;

   typedef double _max_angular_speed_type;
  _max_angular_speed_type max_angular_speed;

   typedef double _max_centripetal_acceleration_type;
  _max_centripetal_acceleration_type max_centripetal_acceleration;





  typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetNavCriteriaPlanRequest_

typedef ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<std::allocator<void> > GetNavCriteriaPlanRequest;

typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest > GetNavCriteriaPlanRequestPtr;
typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest const> GetNavCriteriaPlanRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator1> & lhs, const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator2> & rhs)
{
  return lhs.acceleration == rhs.acceleration &&
    lhs.max_linear_speed == rhs.max_linear_speed &&
    lhs.max_angular_speed == rhs.max_angular_speed &&
    lhs.max_centripetal_acceleration == rhs.max_centripetal_acceleration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator1> & lhs, const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ROS_SplinePathMotionProfiling

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edb38829b81d2cf836e0906f3ace6437";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xedb38829b81d2cf8ULL;
  static const uint64_t static_value2 = 0x36e0906f3ace6437ULL;
};

template<class ContainerAllocator>
struct DataType< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ROS_SplinePathMotionProfiling/GetNavCriteriaPlanRequest";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 acceleration\n"
"float64 max_linear_speed\n"
"float64 max_angular_speed\n"
"float64 max_centripetal_acceleration\n"
;
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.acceleration);
      stream.next(m.max_linear_speed);
      stream.next(m.max_angular_speed);
      stream.next(m.max_centripetal_acceleration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetNavCriteriaPlanRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "acceleration: ";
    Printer<double>::stream(s, indent + "  ", v.acceleration);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_linear_speed: ";
    Printer<double>::stream(s, indent + "  ", v.max_linear_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_angular_speed: ";
    Printer<double>::stream(s, indent + "  ", v.max_angular_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_centripetal_acceleration: ";
    Printer<double>::stream(s, indent + "  ", v.max_centripetal_acceleration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVCRITERIAPLANREQUEST_H
