// Generated by gencpp from file ROS_SplinePathMotionProfiling/GetNavSimTestRequest.msg
// DO NOT EDIT!


#ifndef ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVSIMTESTREQUEST_H
#define ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVSIMTESTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ROS_SplinePathMotionProfiling
{
template <class ContainerAllocator>
struct GetNavSimTestRequest_
{
  typedef GetNavSimTestRequest_<ContainerAllocator> Type;

  GetNavSimTestRequest_()
    : linear_kp(0.0)
    , linear_ki(0.0)
    , linear_kd(0.0)
    , angular_kp(0.0)
    , angular_ki(0.0)
    , angular_kd(0.0)  {
    }
  GetNavSimTestRequest_(const ContainerAllocator& _alloc)
    : linear_kp(0.0)
    , linear_ki(0.0)
    , linear_kd(0.0)
    , angular_kp(0.0)
    , angular_ki(0.0)
    , angular_kd(0.0)  {
  (void)_alloc;
    }



   typedef double _linear_kp_type;
  _linear_kp_type linear_kp;

   typedef double _linear_ki_type;
  _linear_ki_type linear_ki;

   typedef double _linear_kd_type;
  _linear_kd_type linear_kd;

   typedef double _angular_kp_type;
  _angular_kp_type angular_kp;

   typedef double _angular_ki_type;
  _angular_ki_type angular_ki;

   typedef double _angular_kd_type;
  _angular_kd_type angular_kd;





  typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetNavSimTestRequest_

typedef ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<std::allocator<void> > GetNavSimTestRequest;

typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest > GetNavSimTestRequestPtr;
typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest const> GetNavSimTestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator1> & lhs, const ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.linear_kp == rhs.linear_kp &&
    lhs.linear_ki == rhs.linear_ki &&
    lhs.linear_kd == rhs.linear_kd &&
    lhs.angular_kp == rhs.angular_kp &&
    lhs.angular_ki == rhs.angular_ki &&
    lhs.angular_kd == rhs.angular_kd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator1> & lhs, const ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ROS_SplinePathMotionProfiling

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bfa9d35973564078f2fc6870ea560295";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbfa9d35973564078ULL;
  static const uint64_t static_value2 = 0xf2fc6870ea560295ULL;
};

template<class ContainerAllocator>
struct DataType< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ROS_SplinePathMotionProfiling/GetNavSimTestRequest";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 linear_kp\n"
"float64 linear_ki\n"
"float64 linear_kd \n"
"float64 angular_kp\n"
"float64 angular_ki\n"
"float64 angular_kd\n"
;
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_kp);
      stream.next(m.linear_ki);
      stream.next(m.linear_kd);
      stream.next(m.angular_kp);
      stream.next(m.angular_ki);
      stream.next(m.angular_kd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetNavSimTestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "linear_kp: ";
    Printer<double>::stream(s, indent + "  ", v.linear_kp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "linear_ki: ";
    Printer<double>::stream(s, indent + "  ", v.linear_ki);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "linear_kd: ";
    Printer<double>::stream(s, indent + "  ", v.linear_kd);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angular_kp: ";
    Printer<double>::stream(s, indent + "  ", v.angular_kp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angular_ki: ";
    Printer<double>::stream(s, indent + "  ", v.angular_ki);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angular_kd: ";
    Printer<double>::stream(s, indent + "  ", v.angular_kd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVSIMTESTREQUEST_H
