// Generated by gencpp from file ROS_SplinePathMotionProfiling/GetNavCriteriaPlanResponse.msg
// DO NOT EDIT!


#ifndef ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVCRITERIAPLANRESPONSE_H
#define ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVCRITERIAPLANRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ROS_SplinePathMotionProfiling
{
template <class ContainerAllocator>
struct GetNavCriteriaPlanResponse_
{
  typedef GetNavCriteriaPlanResponse_<ContainerAllocator> Type;

  GetNavCriteriaPlanResponse_()
    {
    }
  GetNavCriteriaPlanResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetNavCriteriaPlanResponse_

typedef ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<std::allocator<void> > GetNavCriteriaPlanResponse;

typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse > GetNavCriteriaPlanResponsePtr;
typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse const> GetNavCriteriaPlanResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace ROS_SplinePathMotionProfiling

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ROS_SplinePathMotionProfiling/GetNavCriteriaPlanResponse";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetNavCriteriaPlanResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVCRITERIAPLANRESPONSE_H
