// Generated by gencpp from file ROS_SplinePathMotionProfiling/GetNavSimTestResponse.msg
// DO NOT EDIT!


#ifndef ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVSIMTESTRESPONSE_H
#define ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVSIMTESTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ROS_SplinePathMotionProfiling
{
template <class ContainerAllocator>
struct GetNavSimTestResponse_
{
  typedef GetNavSimTestResponse_<ContainerAllocator> Type;

  GetNavSimTestResponse_()
    : x_errors()
    , y_errors()
    , heading_errors()
    , lin_speeds()
    , ang_speeds()
    , lin_speed_adjs()
    , ang_speed_adjs()  {
    }
  GetNavSimTestResponse_(const ContainerAllocator& _alloc)
    : x_errors(_alloc)
    , y_errors(_alloc)
    , heading_errors(_alloc)
    , lin_speeds(_alloc)
    , ang_speeds(_alloc)
    , lin_speed_adjs(_alloc)
    , ang_speed_adjs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _x_errors_type;
  _x_errors_type x_errors;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _y_errors_type;
  _y_errors_type y_errors;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _heading_errors_type;
  _heading_errors_type heading_errors;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _lin_speeds_type;
  _lin_speeds_type lin_speeds;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _ang_speeds_type;
  _ang_speeds_type ang_speeds;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _lin_speed_adjs_type;
  _lin_speed_adjs_type lin_speed_adjs;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _ang_speed_adjs_type;
  _ang_speed_adjs_type ang_speed_adjs;





  typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetNavSimTestResponse_

typedef ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<std::allocator<void> > GetNavSimTestResponse;

typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse > GetNavSimTestResponsePtr;
typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse const> GetNavSimTestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator1> & lhs, const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x_errors == rhs.x_errors &&
    lhs.y_errors == rhs.y_errors &&
    lhs.heading_errors == rhs.heading_errors &&
    lhs.lin_speeds == rhs.lin_speeds &&
    lhs.ang_speeds == rhs.ang_speeds &&
    lhs.lin_speed_adjs == rhs.lin_speed_adjs &&
    lhs.ang_speed_adjs == rhs.ang_speed_adjs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator1> & lhs, const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ROS_SplinePathMotionProfiling

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4824d49aad876fcf1e7bb0e52ff3ea6";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4824d49aad876fcULL;
  static const uint64_t static_value2 = 0xf1e7bb0e52ff3ea6ULL;
};

template<class ContainerAllocator>
struct DataType< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ROS_SplinePathMotionProfiling/GetNavSimTestResponse";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] x_errors\n"
"float64[] y_errors\n"
"float64[] heading_errors\n"
"float64[] lin_speeds\n"
"float64[] ang_speeds\n"
"float64[] lin_speed_adjs \n"
"float64[] ang_speed_adjs\n"
;
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_errors);
      stream.next(m.y_errors);
      stream.next(m.heading_errors);
      stream.next(m.lin_speeds);
      stream.next(m.ang_speeds);
      stream.next(m.lin_speed_adjs);
      stream.next(m.ang_speed_adjs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetNavSimTestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x_errors: ";
    if (v.x_errors.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.x_errors.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.x_errors[i]);
    }
    if (v.x_errors.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_errors: ";
    if (v.y_errors.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.y_errors.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.y_errors[i]);
    }
    if (v.y_errors.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "heading_errors: ";
    if (v.heading_errors.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.heading_errors.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.heading_errors[i]);
    }
    if (v.heading_errors.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lin_speeds: ";
    if (v.lin_speeds.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.lin_speeds.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.lin_speeds[i]);
    }
    if (v.lin_speeds.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ang_speeds: ";
    if (v.ang_speeds.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.ang_speeds.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.ang_speeds[i]);
    }
    if (v.ang_speeds.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lin_speed_adjs: ";
    if (v.lin_speed_adjs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.lin_speed_adjs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.lin_speed_adjs[i]);
    }
    if (v.lin_speed_adjs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ang_speed_adjs: ";
    if (v.ang_speed_adjs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.ang_speed_adjs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.ang_speed_adjs[i]);
    }
    if (v.ang_speed_adjs.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVSIMTESTRESPONSE_H
