// Generated by gencpp from file ROS_SplinePathMotionProfiling/GetNavSimTestResponse.msg
// DO NOT EDIT!


#ifndef ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVSIMTESTRESPONSE_H
#define ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVSIMTESTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ROS_SplinePathMotionProfiling
{
template <class ContainerAllocator>
struct GetNavSimTestResponse_
{
  typedef GetNavSimTestResponse_<ContainerAllocator> Type;

  GetNavSimTestResponse_()
    : position_error(0.0)
    , heading_error(0.0)  {
    }
  GetNavSimTestResponse_(const ContainerAllocator& _alloc)
    : position_error(0.0)
    , heading_error(0.0)  {
  (void)_alloc;
    }



   typedef double _position_error_type;
  _position_error_type position_error;

   typedef double _heading_error_type;
  _heading_error_type heading_error;





  typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetNavSimTestResponse_

typedef ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<std::allocator<void> > GetNavSimTestResponse;

typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse > GetNavSimTestResponsePtr;
typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse const> GetNavSimTestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator1> & lhs, const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.position_error == rhs.position_error &&
    lhs.heading_error == rhs.heading_error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator1> & lhs, const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ROS_SplinePathMotionProfiling

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aff0bad24a3a18f4048667c38924dc82";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaff0bad24a3a18f4ULL;
  static const uint64_t static_value2 = 0x048667c38924dc82ULL;
};

template<class ContainerAllocator>
struct DataType< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ROS_SplinePathMotionProfiling/GetNavSimTestResponse";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 position_error\n"
"float64 heading_error\n"
;
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position_error);
      stream.next(m.heading_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetNavSimTestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "position_error: ";
    Printer<double>::stream(s, indent + "  ", v.position_error);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "heading_error: ";
    Printer<double>::stream(s, indent + "  ", v.heading_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVSIMTESTRESPONSE_H
