// Generated by gencpp from file ROS_SplinePathMotionProfiling/GetNavSimTest.msg
// DO NOT EDIT!


#ifndef ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVSIMTEST_H
#define ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVSIMTEST_H

#include <ros/service_traits.h>


#include <ROS_SplinePathMotionProfiling/GetNavSimTestRequest.h>
#include <ROS_SplinePathMotionProfiling/GetNavSimTestResponse.h>


namespace ROS_SplinePathMotionProfiling
{

struct GetNavSimTest
{

typedef GetNavSimTestRequest Request;
typedef GetNavSimTestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNavSimTest
} // namespace ROS_SplinePathMotionProfiling


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavSimTest > {
  static const char* value()
  {
    return "5f1ff2380d967c102097eb58066e53b1";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavSimTest&) { return value(); }
};

template<>
struct DataType< ::ROS_SplinePathMotionProfiling::GetNavSimTest > {
  static const char* value()
  {
    return "ROS_SplinePathMotionProfiling/GetNavSimTest";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavSimTest&) { return value(); }
};


// service_traits::MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest> should match
// service_traits::MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavSimTest >
template<>
struct MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavSimTest >::value();
  }
  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest> should match
// service_traits::DataType< ::ROS_SplinePathMotionProfiling::GetNavSimTest >
template<>
struct DataType< ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest>
{
  static const char* value()
  {
    return DataType< ::ROS_SplinePathMotionProfiling::GetNavSimTest >::value();
  }
  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavSimTestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse> should match
// service_traits::MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavSimTest >
template<>
struct MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavSimTest >::value();
  }
  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse> should match
// service_traits::DataType< ::ROS_SplinePathMotionProfiling::GetNavSimTest >
template<>
struct DataType< ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse>
{
  static const char* value()
  {
    return DataType< ::ROS_SplinePathMotionProfiling::GetNavSimTest >::value();
  }
  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavSimTestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVSIMTEST_H
