// Generated by gencpp from file ROS_SplinePathMotionProfiling/GetNavCriteriaPlan.msg
// DO NOT EDIT!


#ifndef ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVCRITERIAPLAN_H
#define ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVCRITERIAPLAN_H

#include <ros/service_traits.h>


#include <ROS_SplinePathMotionProfiling/GetNavCriteriaPlanRequest.h>
#include <ROS_SplinePathMotionProfiling/GetNavCriteriaPlanResponse.h>


namespace ROS_SplinePathMotionProfiling
{

struct GetNavCriteriaPlan
{

typedef GetNavCriteriaPlanRequest Request;
typedef GetNavCriteriaPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNavCriteriaPlan
} // namespace ROS_SplinePathMotionProfiling


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlan > {
  static const char* value()
  {
    return "edb38829b81d2cf836e0906f3ace6437";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlan&) { return value(); }
};

template<>
struct DataType< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlan > {
  static const char* value()
  {
    return "ROS_SplinePathMotionProfiling/GetNavCriteriaPlan";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlan&) { return value(); }
};


// service_traits::MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest> should match
// service_traits::MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlan >
template<>
struct MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlan >::value();
  }
  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest> should match
// service_traits::DataType< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlan >
template<>
struct DataType< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest>
{
  static const char* value()
  {
    return DataType< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlan >::value();
  }
  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse> should match
// service_traits::MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlan >
template<>
struct MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlan >::value();
  }
  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse> should match
// service_traits::DataType< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlan >
template<>
struct DataType< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse>
{
  static const char* value()
  {
    return DataType< ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlan >::value();
  }
  static const char* value(const ::ROS_SplinePathMotionProfiling::GetNavCriteriaPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETNAVCRITERIAPLAN_H
