// Generated by gencpp from file ROS_SplinePathMotionProfiling/GetSimpleSplinePlanRequest.msg
// DO NOT EDIT!


#ifndef ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETSIMPLESPLINEPLANREQUEST_H
#define ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETSIMPLESPLINEPLANREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>

namespace ROS_SplinePathMotionProfiling
{
template <class ContainerAllocator>
struct GetSimpleSplinePlanRequest_
{
  typedef GetSimpleSplinePlanRequest_<ContainerAllocator> Type;

  GetSimpleSplinePlanRequest_()
    : waypoints_path()  {
    }
  GetSimpleSplinePlanRequest_(const ContainerAllocator& _alloc)
    : waypoints_path(_alloc)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::Path_<ContainerAllocator>  _waypoints_path_type;
  _waypoints_path_type waypoints_path;





  typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetSimpleSplinePlanRequest_

typedef ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<std::allocator<void> > GetSimpleSplinePlanRequest;

typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest > GetSimpleSplinePlanRequestPtr;
typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest const> GetSimpleSplinePlanRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator1> & lhs, const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator2> & rhs)
{
  return lhs.waypoints_path == rhs.waypoints_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator1> & lhs, const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ROS_SplinePathMotionProfiling

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8513d5adc60aaa265ef7eb12426b376c";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8513d5adc60aaa26ULL;
  static const uint64_t static_value2 = 0x5ef7eb12426b376cULL;
};

template<class ContainerAllocator>
struct DataType< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ROS_SplinePathMotionProfiling/GetSimpleSplinePlanRequest";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_msgs/Path waypoints_path\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSimpleSplinePlanRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "waypoints_path: ";
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.waypoints_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETSIMPLESPLINEPLANREQUEST_H
