// Generated by gencpp from file ROS_SplinePathMotionProfiling/GetSimpleSplinePlan.msg
// DO NOT EDIT!


#ifndef ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETSIMPLESPLINEPLAN_H
#define ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETSIMPLESPLINEPLAN_H

#include <ros/service_traits.h>


#include <ROS_SplinePathMotionProfiling/GetSimpleSplinePlanRequest.h>
#include <ROS_SplinePathMotionProfiling/GetSimpleSplinePlanResponse.h>


namespace ROS_SplinePathMotionProfiling
{

struct GetSimpleSplinePlan
{

typedef GetSimpleSplinePlanRequest Request;
typedef GetSimpleSplinePlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSimpleSplinePlan
} // namespace ROS_SplinePathMotionProfiling


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlan > {
  static const char* value()
  {
    return "e353426b0fcb97acfb6082534ab67613";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlan&) { return value(); }
};

template<>
struct DataType< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlan > {
  static const char* value()
  {
    return "ROS_SplinePathMotionProfiling/GetSimpleSplinePlan";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlan&) { return value(); }
};


// service_traits::MD5Sum< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest> should match
// service_traits::MD5Sum< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlan >
template<>
struct MD5Sum< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlan >::value();
  }
  static const char* value(const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest> should match
// service_traits::DataType< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlan >
template<>
struct DataType< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest>
{
  static const char* value()
  {
    return DataType< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlan >::value();
  }
  static const char* value(const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse> should match
// service_traits::MD5Sum< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlan >
template<>
struct MD5Sum< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlan >::value();
  }
  static const char* value(const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse> should match
// service_traits::DataType< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlan >
template<>
struct DataType< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse>
{
  static const char* value()
  {
    return DataType< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlan >::value();
  }
  static const char* value(const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETSIMPLESPLINEPLAN_H
