// Generated by gencpp from file ROS_SplinePathMotionProfiling/GetSimpleSplinePlanResponse.msg
// DO NOT EDIT!


#ifndef ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETSIMPLESPLINEPLANRESPONSE_H
#define ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETSIMPLESPLINEPLANRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>

namespace ROS_SplinePathMotionProfiling
{
template <class ContainerAllocator>
struct GetSimpleSplinePlanResponse_
{
  typedef GetSimpleSplinePlanResponse_<ContainerAllocator> Type;

  GetSimpleSplinePlanResponse_()
    : spline_path()
    , sd_steps()
    , cumulative_sd_steps()  {
    }
  GetSimpleSplinePlanResponse_(const ContainerAllocator& _alloc)
    : spline_path(_alloc)
    , sd_steps(_alloc)
    , cumulative_sd_steps(_alloc)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::Path_<ContainerAllocator>  _spline_path_type;
  _spline_path_type spline_path;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _sd_steps_type;
  _sd_steps_type sd_steps;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _cumulative_sd_steps_type;
  _cumulative_sd_steps_type cumulative_sd_steps;





  typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetSimpleSplinePlanResponse_

typedef ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<std::allocator<void> > GetSimpleSplinePlanResponse;

typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse > GetSimpleSplinePlanResponsePtr;
typedef boost::shared_ptr< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse const> GetSimpleSplinePlanResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator1> & lhs, const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator2> & rhs)
{
  return lhs.spline_path == rhs.spline_path &&
    lhs.sd_steps == rhs.sd_steps &&
    lhs.cumulative_sd_steps == rhs.cumulative_sd_steps;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator1> & lhs, const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ROS_SplinePathMotionProfiling

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dfa6242b0f40a356164a25a6d0f02974";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdfa6242b0f40a356ULL;
  static const uint64_t static_value2 = 0x164a25a6d0f02974ULL;
};

template<class ContainerAllocator>
struct DataType< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ROS_SplinePathMotionProfiling/GetSimpleSplinePlanResponse";
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_msgs/Path spline_path\n"
"float64[] sd_steps \n"
"float64[] cumulative_sd_steps\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.spline_path);
      stream.next(m.sd_steps);
      stream.next(m.cumulative_sd_steps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSimpleSplinePlanResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ROS_SplinePathMotionProfiling::GetSimpleSplinePlanResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "spline_path: ";
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.spline_path);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sd_steps: ";
    if (v.sd_steps.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.sd_steps.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.sd_steps[i]);
    }
    if (v.sd_steps.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cumulative_sd_steps: ";
    if (v.cumulative_sd_steps.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.cumulative_sd_steps.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.cumulative_sd_steps[i]);
    }
    if (v.cumulative_sd_steps.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SPLINEPATHMOTIONPROFILING_MESSAGE_GETSIMPLESPLINEPLANRESPONSE_H
