# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ROS_SplinePathMotionProfiling/GetNavSimTestRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GetNavSimTestRequest(genpy.Message):
  _md5sum = "bfa9d35973564078f2fc6870ea560295"
  _type = "ROS_SplinePathMotionProfiling/GetNavSimTestRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 linear_kp
float64 linear_ki
float64 linear_kd 
float64 angular_kp
float64 angular_ki
float64 angular_kd
"""
  __slots__ = ['linear_kp','linear_ki','linear_kd','angular_kp','angular_ki','angular_kd']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       linear_kp,linear_ki,linear_kd,angular_kp,angular_ki,angular_kd

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetNavSimTestRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.linear_kp is None:
        self.linear_kp = 0.
      if self.linear_ki is None:
        self.linear_ki = 0.
      if self.linear_kd is None:
        self.linear_kd = 0.
      if self.angular_kp is None:
        self.angular_kp = 0.
      if self.angular_ki is None:
        self.angular_ki = 0.
      if self.angular_kd is None:
        self.angular_kd = 0.
    else:
      self.linear_kp = 0.
      self.linear_ki = 0.
      self.linear_kd = 0.
      self.angular_kp = 0.
      self.angular_ki = 0.
      self.angular_kd = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.linear_kp, _x.linear_ki, _x.linear_kd, _x.angular_kp, _x.angular_ki, _x.angular_kd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.linear_kp, _x.linear_ki, _x.linear_kd, _x.angular_kp, _x.angular_ki, _x.angular_kd,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.linear_kp, _x.linear_ki, _x.linear_kd, _x.angular_kp, _x.angular_ki, _x.angular_kd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.linear_kp, _x.linear_ki, _x.linear_kd, _x.angular_kp, _x.angular_ki, _x.angular_kd,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ROS_SplinePathMotionProfiling/GetNavSimTestResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GetNavSimTestResponse(genpy.Message):
  _md5sum = "aff0bad24a3a18f4048667c38924dc82"
  _type = "ROS_SplinePathMotionProfiling/GetNavSimTestResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 position_error
float64 heading_error
"""
  __slots__ = ['position_error','heading_error']
  _slot_types = ['float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       position_error,heading_error

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetNavSimTestResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.position_error is None:
        self.position_error = 0.
      if self.heading_error is None:
        self.heading_error = 0.
    else:
      self.position_error = 0.
      self.heading_error = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2d().pack(_x.position_error, _x.heading_error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.position_error, _x.heading_error,) = _get_struct_2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2d().pack(_x.position_error, _x.heading_error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.position_error, _x.heading_error,) = _get_struct_2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d = None
def _get_struct_2d():
    global _struct_2d
    if _struct_2d is None:
        _struct_2d = struct.Struct("<2d")
    return _struct_2d
class GetNavSimTest(object):
  _type          = 'ROS_SplinePathMotionProfiling/GetNavSimTest'
  _md5sum = '5f1ff2380d967c102097eb58066e53b1'
  _request_class  = GetNavSimTestRequest
  _response_class = GetNavSimTestResponse
