(cl:defpackage ROS_SplinePathMotionProfiling-srv
  (:use )
  (:export
   "GETNAVCRITERIAPLAN"
   "<GETNAVCRITERIAPLAN-REQUEST>"
   "GETNAVCRITERIAPLAN-REQUEST"
   "<GETNAVCRITERIAPLAN-RESPONSE>"
   "GETNAVCRITERIAPLAN-RESPONSE"
   "GETNAVSIMTEST"
   "<GETNAVSIMTEST-REQUEST>"
   "GETNAVSIMTEST-REQUEST"
   "<GETNAVSIMTEST-RESPONSE>"
   "GETNAVSIMTEST-RESPONSE"
   "GETSIMPLESPLINEPLAN"
   "<GETSIMPLESPLINEPLAN-REQUEST>"
   "GETSIMPLESPLINEPLAN-REQUEST"
   "<GETSIMPLESPLINEPLAN-RESPONSE>"
   "GETSIMPLESPLINEPLAN-RESPONSE"
  ))

